from __future__ import annotations

import os

MODEL_RETRIEVAL_FUNCTION_ID = 21002

# 检索命中阈值（距离越小越相似）。
# 可通过环境变量 CORONA_SEARCH_DISTANCE_THRESHOLD 覆盖，默认值放宽到 1.0。
SEARCH_DISTANCE_THRESHOLD = float(os.getenv("CORONA_SEARCH_DISTANCE_THRESHOLD", "1.0"))
SEARCH_MAX_WORKERS = 1
GENERATION_MAX_WORKERS = 1
